packages:
  base: !include base_esp32_host.yaml  # see above

substitutions:
  # Screen Size
  screen_height_px: '480'
  screen_width_px: '480'

esphome:
  name: sdl
  friendly_name: SignalK SDL Display

# SDL display requires SDL2 development packages (sdl2-config).
# Uncomment these blocks after installing SDL2 on your system.
# display:
#   - platform: sdl
#     id: my_display
#     show_test_card: true
#     dimensions:
#       width: $screen_width_px
#       height: $screen_height_px
#
# touchscreen:
#   - platform: sdl
#     id: my_touchscreen
#     display: my_display

# number:
#   - platform: signalk
#     id: steering_autopilot_target
#     path: steering.autopilot.target
#     units: degrees

sensor:
  - platform: signalk
    id: navigation_speedOverGround
    path: navigation.speedOverGround
    unit: "knots"
    accuracy_decimals: 2
    on_value:
      - logger.log:
          format: "SOG %.1f"
          args: ['x']
          level: DEBUG
# lvgl:
#   widgets:
#     - label:
#         id: sog_label
#         align: CENTER
#     - label:
#         id: sog_label1
#         align: CENTER
#         y: 50
#
#     - button:
#         width: 100
#         height: 100
#         bg_color: 0xc70814
#         widgets:
#           - label:
#               text: "WIND"
#         on_press:
#           - signalk.put_request:
#               path: steering.autopilot.state
#               value: "wind"
